/* tslint:disable */
/* eslint-disable */
export const memory: WebAssembly.Memory;
export function statement_from_journal_bytes(a: number, b: number, c: number): void;
export function sys_panic(a: number, b: number): void;
export function sys_pause(a: number, b: number): void;
export function sys_halt(a: number, b: number): void;
export function sys_rand(a: number, b: number): void;
export function syscall_2(a: number, b: number, c: number, d: number, e: number, f: number): void;
export function sys_verify_integrity(a: number, b: number): void;
export function sys_cycle_count(): number;
export function sys_log(a: number, b: number): void;
export function sys_read(a: number, b: number, c: number): number;
export function sys_read_words(a: number, b: number, c: number): number;
export function sys_input(a: number): number;
export function sys_sha_buffer(a: number, b: number, c: number, d: number): void;
export function sys_sha_compress(a: number, b: number, c: number, d: number): void;
export function sys_bigint(a: number, b: number, c: number, d: number, e: number): void;
export function sys_write(a: number, b: number, c: number): void;
export function sys_getenv(a: number, b: number, c: number, d: number): number;
export function sys_argc(): number;
export function sys_argv(a: number, b: number, c: number): number;
export function sys_alloc_words(a: number): number;
export function sys_alloc_aligned(a: number, b: number): number;
export function syscall_0(a: number, b: number, c: number, d: number): void;
export function syscall_1(a: number, b: number, c: number, d: number, e: number): void;
export function syscall_3(a: number, b: number, c: number, d: number, e: number, f: number, g: number): void;
export function syscall_4(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number): void;
export function syscall_5(a: number, b: number, c: number, d: number, e: number, f: number, g: number, h: number, i: number): void;
export function __wbindgen_add_to_stack_pointer(a: number): number;
export function __wbindgen_malloc(a: number, b: number): number;
